# This is the mods.toml file for Re-MemoryUsageBar.
# The overall format is standard TOML format, v0.5.0.

modLoader = "javafml" # Mandatory: Mod loader type
loaderVersion = "[47.4.0]" # Mandatory: Forge version range

license = "GPL-3.0" # License for the mod

authors = "Flechazo" # Author of the mod

[[mods]] # Mandatory: List of mods
modId = "rememoryusagebar" # Mandatory: Mod ID
version = "1.0.0" # Mandatory: Mod version
displayName = "Re-MemoryUsageBar" # Mandatory: Display name for the mod
description = '''1.20.1forge reset of MemoryUsageBar''' # Mandatory: Description text for the mod (multi line!)

[[dependencies.rememoryusagebar]] # Optional: Dependency on Forge
modId = "forge" # Mandatory: Dependency mod ID
mandatory = true # Mandatory: Is this dependency required?
versionRange = "[47.3.0]" # Mandatory: Version range for the dependency
ordering = "NONE" # Optional: Ordering relationship for the dependency
side = "BOTH" # Optional: Side this dependency applies to

[[dependencies.rememoryusagebar]] # Optional: Dependency on Minecraft
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.4)" # Specifies a minimum of 1.20.1 up to but not including 1.20.4
ordering = "NONE"
side = "BOTH"